=== uncefact/spec-untp/data-models/untp-svc/artefacts/ConformitySchemeVocabulary-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "type": {
      "type": "string",
      "default": "ConformitySchemeVocabulary",
      "enum": [
        "ConformitySchemeVocabulary"
      ]
    },
    "id": {
      "type": "string",
      "format": "uri",
      "description": "The identifier of this scheme as a URI. Typically of the form ownerDomain.schemeName."
    },
    "name": {
      "type": "string",
      "description": "The name of this conformity scheme"
    },
    "description": {
      "type": "string",
      "description": "The description of this conformity scheme"
    },
    "version": {
      "type": "string",
      "description": "Version of this scheme folling SemVer best practive (major.minor.patch). "
    },
    "validFrom": {
      "type": "string",
      "format": "date",
      "description": "The data from which this scheme version is valid."
    },
    "owner": {
      "type": "object",
      "properties": {
        "id": {
          "example": "https://abr.business.gov.au/ABN/View?abn=90664869327",
          "type": "string",
          "format": "uri",
          "description": "The globally unique ID of the party as a URI, ideally as a resolvable ID. "
        },
        "name": {
          "example": "Sample Company Pty Ltd.",
          "type": "string",
          "description": "The registered name of the party within the identifier scheme."
        },
        "registeredId": {
          "example": 90664869327,
          "type": "string",
          "description": "The registration number (alphanumeric) of the Party within the register. Unique within the register."
        }
      },
      "required": [
        "id",
        "name"
      ],
      "description": "The party that is the owner / maintainer of this conformity scheme."
    },
    "trustMark": {
      "type": "string",
      "format": "binary",
      "description": "The trust mark or seal used by this conformity scheme."
    },
    "@type": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": ""
    },
    "@context": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": ""
    },
    "conformityCriterion": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/ConformityCriterion"
      },
      "description": "A list of criterion defined by this scheme."
    },
    "regulatoryAlignment": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/Regulation"
      },
      "description": "Regulations to which this conformity scheme is aligned. "
    },
    "industryScope": {
      "$ref": "#/$defs/Classification",
      "description": "A classification scheme and code / name representing a category value for a product, entity, or facility."
    },
    "geographicScope": {
      "$ref": "#/$defs/Classification",
      "description": "A classification scheme and code / name representing a category value for a product, entity, or facility."
    },
    "performanceLevelCodes": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/LevelCode"
      },
      "description": "An optional list of performance levels (eg C, B, A, AA) defined by the scheme and used to assign criterion to the relevant performance level."
    },
    "tagCodes": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/TagCode"
      },
      "description": "A codelist of tags defined by the scheme and used to tag criterion for filtering and sorting."
    }
  },
  "description": "A conformity scheme as a structured hierarchy of conformity critera.",
  "required": [
    "id",
    "name",
    "description",
    "version",
    "validFrom",
    "owner",
    "conformityCriterion"
  ],
  "$defs": {
    "ConformityCriterion": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "default": "ConformityCriterion",
          "enum": [
            "ConformityCriterion"
          ]
        },
        "id": {
          "example": "https://www.globalbattery.org/media/publications/gba-rulebook-v2.0-master.pdf#BatteryAssembly",
          "type": "string",
          "format": "uri",
          "description": "A unique identifier for the criterion within the scheme, standard  or regulation. For example CO2 emissions calculations for liquid fuel combustion."
        },
        "name": {
          "example": "GBA Battery rule book v2.0 battery assembly guidelines.",
          "type": "string",
          "description": "A name that describes this criteria."
        },
        "description": {
          "type": "string",
          "description": "A full text description of the criterion that clearly specifies how compliance is achieved and measured. "
        },
        "conformityTopic": {
          "type": "string",
          "enum": [
            "environment.energy",
            "environment.emissions",
            "environment.water",
            "environment.waste",
            "environment.deforestation",
            "environment.biodiversity",
            "circularity.content",
            "circularity.design",
            "social.labour",
            "social.rights",
            "social.community",
            "social.safety",
            "governance.ethics",
            "governance.compliance",
            "governance.transparency"
          ],
          "example": "environment.energy",
          "description": "A gloabl UN/CEFACT standard sustainability toipic code. "
        },
        "status": {
          "type": "string",
          "enum": [
            "proposed",
            "active",
            "deprecated"
          ],
          "example": "proposed",
          "description": "The lifecycle status of this criterion. "
        },
        "thresholdValue": {
          "$ref": "#/$defs/Metric",
          "description": "A threshold value that defines the minimum compliance level. "
        },
        "performanceLevel": {
          "type": "string",
          "description": "A performance category code to group criterion in a given hierarchyLevel according to pareformance"
        },
        "tags": {
          "type": "string",
          "description": "a category code to reporent target stakholder types or commodity types to which this criteron applies. "
        },
        "subCriterion": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ConformityCriterion"
          },
          "description": "A list of sub-criteria under this criterion."
        },
        "category": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Classification"
          },
          "description": "A set of classification codes that may be used to catgorise the applicability of this criteria - for example industry sector, jurisdiction, commodity type."
        }
      },
      "description": "A conformity criterion under the scheme. Note that the same criterion ID may be reused across multiple schemes (particularly across different versions of the same scheme).",
      "required": [
        "id",
        "name",
        "description",
        "conformityTopic",
        "status"
      ]
    },
    "Metric": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "metricName": {
          "example": "GHG emissions intensity",
          "type": "string",
          "description": "A human readable name for this metric (for example \"Tensile strength\")"
        },
        "metricValue": {
          "$ref": "#/$defs/Measure",
          "description": "A numeric value and unit of measure for this metric. Could be a measured value or a specified threshold. Eg {\"value\":400, \"unit\":\"MPA\"} as tensile strength of structural steel"
        },
        "score": {
          "example": "BB",
          "type": "string",
          "description": "A score or rank associated with this measured metric."
        },
        "accuracy": {
          "example": 0.05,
          "type": "number",
          "description": "A percentage represented as a numeric between 0 and 1 indicating the rage of accuracy of the claimed value (eg 0.05 means that the actual value is within 5% of the claimed value.)"
        }
      },
      "description": "A specific measure of performance against the criteria that governs the claim.  Expressed as an array of metric (ie unit of measure) / value (ie the actual numeric value) pairs.  ",
      "required": [
        "metricName",
        "metricValue"
      ]
    },
    "Measure": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "value": {
          "example": 10,
          "type": "number",
          "description": "The numeric value of the measure"
        },
        "unit": {
          "type": "string",
          "x-external-enumeration": "https://vocabulary.uncefact.org/UnitMeasureCode",
          "description": "Unit of measure drawn from the UNECE Rec20 measure code list.\n\n    This is an enumerated value, but the list of valid values are too big, or change too often to include here. You can access the list of allowable values at this URL:  https://vocabulary.uncefact.org/UnitMeasureCode\n    "
        }
      },
      "description": "The measure class defines a numeric measured value (eg 10) and a coded unit of measure (eg KG).",
      "required": [
        "value",
        "unit"
      ]
    },
    "Classification": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "default": "Classification",
          "enum": [
            "Classification"
          ]
        },
        "id": {
          "example": "https://unstats.un.org/unsd/classifications/Econ/cpc/46410",
          "type": "string",
          "format": "uri",
          "description": "The globally unique URI representing the specific classifier value"
        },
        "code": {
          "example": 46410,
          "type": "string",
          "description": "classification code within the scheme"
        },
        "name": {
          "example": "Primary cells and primary batteries",
          "type": "string",
          "description": "Name of the classification represented by the code"
        },
        "schemeID": {
          "example": "https://unstats.un.org/unsd/classifications/Econ/cpc/",
          "type": "string",
          "format": "uri",
          "description": "Classification scheme ID"
        },
        "schemeName": {
          "example": "UN Central Product Classification (CPC)",
          "type": "string",
          "description": "The name of the classification scheme"
        }
      },
      "description": "A classification scheme and code / name representing a category value for a product, entity, or facility.",
      "required": [
        "id",
        "name"
      ]
    },
    "Regulation": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "default": "Regulation",
          "enum": [
            "Regulation"
          ]
        },
        "id": {
          "example": "https://www.legislation.gov.au/F2008L02309/latest/versions",
          "type": "string",
          "format": "uri",
          "description": "The globally unique identifier of this regulation. "
        },
        "name": {
          "example": "NNational Greenhouse and Energy Reporting (Measurement) Determination",
          "type": "string",
          "description": "The name of the regulation or act."
        },
        "jurisdictionCountry": {
          "type": "string",
          "x-external-enumeration": "https://vocabulary.uncefact.org/CountryId",
          "description": "The legal jurisdiction (country) under which the regulation is issued.\n\n    This is an enumerated value, but the list of valid values are too big, or change too often to include here. You can access the list of allowable values at this URL:  https://vocabulary.uncefact.org/CountryId\n    "
        },
        "administeredBy": {
          "type": "object",
          "properties": {
            "id": {
              "example": "https://abr.business.gov.au/ABN/View?abn=90664869327",
              "type": "string",
              "format": "uri",
              "description": "The globally unique ID of the party as a URI, ideally as a resolvable ID. "
            },
            "name": {
              "example": "Sample Company Pty Ltd.",
              "type": "string",
              "description": "The registered name of the party within the identifier scheme."
            },
            "registeredId": {
              "example": 90664869327,
              "type": "string",
              "description": "The registration number (alphanumeric) of the Party within the register. Unique within the register."
            }
          },
          "required": [
            "id",
            "name"
          ],
          "description": "the issuing body of the regulation. For example Australian Government Department of Climate Change, Energy, the Environment and Water"
        },
        "effectiveDate": {
          "example": "2024-03-20",
          "type": "string",
          "format": "date",
          "description": "the date at which the regulation came into effect."
        }
      },
      "description": "A regulation (eg EU deforestation regulation) that defines the criteria for assessment.",
      "required": [
        "administeredBy"
      ]
    },
    "LevelCode": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the performance level (eg \"B\")"
        },
        "rank": {
          "type": "integer",
          "description": "The rank of the conformance level where a higher number indicates a higher performance. "
        },
        "description": {
          "type": "string",
          "description": "A description of this conformity performance level within the scheme."
        }
      },
      "description": "A list of performance level codes that may be assigned to criterion. Conformity at a higher level requires conformity agaisnt all criteria at lower levels.",
      "required": [
        "name",
        "rank"
      ]
    },
    "TagCode": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "description": "Tag name used to classify criterion"
        },
        "description": {
          "type": "string",
          "description": "A full text description of the criterion that clearly specifies how compliance is achieved and measured. "
        }
      },
      "description": "A code list of target groups () that are the object of confomance for this scheme.",
      "required": [
        "name",
        "description"
      ]
    }
  }
}

=== uncefact/spec-untp/data-models/artefacts/ConformitySchemeVocabulary-instance.json
{
  "id": "https://jargon.sh",
  "name": "The quick brown fox jumps over the lazy dog.",
  "description": "The quick brown fox jumps over the lazy dog.",
  "version": "The quick brown fox jumps over the lazy dog.",
  "validFrom": "1970-01-01",
  "owner": {
    "id": "https://abr.business.gov.au/ABN/View?abn=90664869327",
    "name": "Sample Company Pty Ltd.",
    "registeredId": "90664869327",
    "idScheme": {
      "id": "https://id.gs1.org/01/",
      "name": "Global Trade Identification Number (GTIN)"
    }
  },
  "trustMark": "undefined",
  "conformityCriterion": [
    {
      "id": "https://www.globalbattery.org/media/publications/gba-rulebook-v2.0-master.pdf#BatteryAssembly",
      "name": "GBA Battery rule book v2.0 battery assembly guidelines.",
      "description": "The quick brown fox jumps over the lazy dog.",
      "conformityTopic": "environment.energy",
      "status": "proposed",
      "thresholdValue": {
        "metricName": "GHG emissions intensity",
        "metricValue": {
          "value": 10,
          "unit": "KGM"
        },
        "score": "BB",
        "accuracy": 0.05
      },
      "performanceLevel": "The quick brown fox jumps over the lazy dog.",
      "tags": "The quick brown fox jumps over the lazy dog.",
      "subCriterion": [
        {
          "id": "https://www.globalbattery.org/media/publications/gba-rulebook-v2.0-master.pdf#BatteryAssembly",
          "name": "GBA Battery rule book v2.0 battery assembly guidelines.",
          "description": "The quick brown fox jumps over the lazy dog.",
          "conformityTopic": "environment.emissions",
          "status": "active",
          "thresholdValue": {
            "metricName": "GHG emissions intensity",
            "metricValue": {
              "value": 10,
              "unit": "KGM"
            },
            "score": "BB",
            "accuracy": 0.05
          },
          "performanceLevel": "The quick brown fox jumps over the lazy dog.",
          "tags": "The quick brown fox jumps over the lazy dog.",
          "subCriterion": [
            {},
            {}
          ],
          "category": [
            {
              "id": "https://unstats.un.org/unsd/classifications/Econ/cpc/46410",
              "code": "46410",
              "name": "Primary cells and primary batteries",
              "schemeID": "https://unstats.un.org/unsd/classifications/Econ/cpc/",
              "schemeName": "UN Central Product Classification (CPC)"
            },
            {
              "id": "https://unstats.un.org/unsd/classifications/Econ/cpc/46410",
              "code": "46410",
              "name": "Primary cells and primary batteries",
              "schemeID": "https://unstats.un.org/unsd/classifications/Econ/cpc/",
              "schemeName": "UN Central Product Classification (CPC)"
            }
          ]
        },
        {
          "id": "https://www.globalbattery.org/media/publications/gba-rulebook-v2.0-master.pdf#BatteryAssembly",
          "name": "GBA Battery rule book v2.0 battery assembly guidelines.",
          "description": "The quick brown fox jumps over the lazy dog.",
          "conformityTopic": "environment.water",
          "status": "deprecated",
          "thresholdValue": {
            "metricName": "GHG emissions intensity",
            "metricValue": {
              "value": 10,
              "unit": "KGM"
            },
            "score": "BB",
            "accuracy": 0.05
          },
          "performanceLevel": "The quick brown fox jumps over the lazy dog.",
          "tags": "The quick brown fox jumps over the lazy dog.",
          "subCriterion": [
            {},
            {}
          ],
          "category": [
            {
              "id": "https://unstats.un.org/unsd/classifications/Econ/cpc/46410",
              "code": "46410",
              "name": "Primary cells and primary batteries",
              "schemeID": "https://unstats.un.org/unsd/classifications/Econ/cpc/",
              "schemeName": "UN Central Product Classification (CPC)"
            },
            {
              "id": "https://unstats.un.org/unsd/classifications/Econ/cpc/46410",
              "code": "46410",
              "name": "Primary cells and primary batteries",
              "schemeID": "https://unstats.un.org/unsd/classifications/Econ/cpc/",
              "schemeName": "UN Central Product Classification (CPC)"
            }
          ]
        }
      ],
      "category": [
        {
          "id": "https://unstats.un.org/unsd/classifications/Econ/cpc/46410",
          "code": "46410",
          "name": "Primary cells and primary batteries",
          "schemeID": "https://unstats.un.org/unsd/classifications/Econ/cpc/",
          "schemeName": "UN Central Product Classification (CPC)"
        },
        {
          "id": "https://unstats.un.org/unsd/classifications/Econ/cpc/46410",
          "code": "46410",
          "name": "Primary cells and primary batteries",
          "schemeID": "https://unstats.un.org/unsd/classifications/Econ/cpc/",
          "schemeName": "UN Central Product Classification (CPC)"
        }
      ]
    },
    {
      "id": "https://www.globalbattery.org/media/publications/gba-rulebook-v2.0-master.pdf#BatteryAssembly",
      "name": "GBA Battery rule book v2.0 battery assembly guidelines.",
      "description": "The quick brown fox jumps over the lazy dog.",
      "conformityTopic": "environment.waste",
      "status": "proposed",
      "thresholdValue": {
        "metricName": "GHG emissions intensity",
        "metricValue": {
          "value": 10,
          "unit": "KGM"
        },
        "score": "BB",
        "accuracy": 0.05
      },
      "performanceLevel": "The quick brown fox jumps over the lazy dog.",
      "tags": "The quick brown fox jumps over the lazy dog.",
      "subCriterion": [
        {
          "id": "https://www.globalbattery.org/media/publications/gba-rulebook-v2.0-master.pdf#BatteryAssembly",
          "name": "GBA Battery rule book v2.0 battery assembly guidelines.",
          "description": "The quick brown fox jumps over the lazy dog.",
          "conformityTopic": "environment.deforestation",
          "status": "active",
          "thresholdValue": {
            "metricName": "GHG emissions intensity",
            "metricValue": {
              "value": 10,
              "unit": "KGM"
            },
            "score": "BB",
            "accuracy": 0.05
          },
          "performanceLevel": "The quick brown fox jumps over the lazy dog.",
          "tags": "The quick brown fox jumps over the lazy dog.",
          "subCriterion": [
            {},
            {}
          ],
          "category": [
            {
              "id": "https://unstats.un.org/unsd/classifications/Econ/cpc/46410",
              "code": "46410",
              "name": "Primary cells and primary batteries",
              "schemeID": "https://unstats.un.org/unsd/classifications/Econ/cpc/",
              "schemeName": "UN Central Product Classification (CPC)"
            },
            {
              "id": "https://unstats.un.org/unsd/classifications/Econ/cpc/46410",
              "code": "46410",
              "name": "Primary cells and primary batteries",
              "schemeID": "https://unstats.un.org/unsd/classifications/Econ/cpc/",
              "schemeName": "UN Central Product Classification (CPC)"
            }
          ]
        },
        {
          "id": "https://www.globalbattery.org/media/publications/gba-rulebook-v2.0-master.pdf#BatteryAssembly",
          "name": "GBA Battery rule book v2.0 battery assembly guidelines.",
          "description": "The quick brown fox jumps over the lazy dog.",
          "conformityTopic": "environment.biodiversity",
          "status": "deprecated",
          "thresholdValue": {
            "metricName": "GHG emissions intensity",
            "metricValue": {
              "value": 10,
              "unit": "KGM"
            },
            "score": "BB",
            "accuracy": 0.05
          },
          "performanceLevel": "The quick brown fox jumps over the lazy dog.",
          "tags": "The quick brown fox jumps over the lazy dog.",
          "subCriterion": [
            {},
            {}
          ],
          "category": [
            {
              "id": "https://unstats.un.org/unsd/classifications/Econ/cpc/46410",
              "code": "46410",
              "name": "Primary cells and primary batteries",
              "schemeID": "https://unstats.un.org/unsd/classifications/Econ/cpc/",
              "schemeName": "UN Central Product Classification (CPC)"
            },
            {
              "id": "https://unstats.un.org/unsd/classifications/Econ/cpc/46410",
              "code": "46410",
              "name": "Primary cells and primary batteries",
              "schemeID": "https://unstats.un.org/unsd/classifications/Econ/cpc/",
              "schemeName": "UN Central Product Classification (CPC)"
            }
          ]
        }
      ],
      "category": [
        {
          "id": "https://unstats.un.org/unsd/classifications/Econ/cpc/46410",
          "code": "46410",
          "name": "Primary cells and primary batteries",
          "schemeID": "https://unstats.un.org/unsd/classifications/Econ/cpc/",
          "schemeName": "UN Central Product Classification (CPC)"
        },
        {
          "id": "https://unstats.un.org/unsd/classifications/Econ/cpc/46410",
          "code": "46410",
          "name": "Primary cells and primary batteries",
          "schemeID": "https://unstats.un.org/unsd/classifications/Econ/cpc/",
          "schemeName": "UN Central Product Classification (CPC)"
        }
      ]
    }
  ],
  "regulatoryAlignment": [
    {
      "id": "https://www.legislation.gov.au/F2008L02309/latest/versions",
      "name": "NNational Greenhouse and Energy Reporting (Measurement) Determination",
      "jurisdictionCountry": "Enumeration Value",
      "administeredBy": {
